import { User, Ticket } from './types';
import { subDays } from 'date-fns';

export const USERS: User[] = [
  { id: 'admin1', name: 'Admin', email: 'admin@example.com', role: 'admin', roles: ['admin'], avatarColor: 'bg-blue-500' },
  { id: 'driver1', name: 'Carlos', email: 'driver@example.com', role: 'chofer', roles: ['chofer'], avatarColor: 'bg-green-500' },
];

export const TICKETS: Omit<Ticket, 'id'>[] = [
  {
    customerName: 'Juan Perez',
    customerPhone: '555-0101',
    addressLink: 'https://maps.google.com/?q=Plaza+de+la+Constitución,Mexico+City',
    status: 'Pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 1,
  },
  {
    customerName: 'Maria Garcia',
    customerPhone: '555-0102',
    addressLink: 'https://maps.google.com/?q=Angel+de+la+Independencia,Mexico+City',
    status: 'Prepared',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 2,
  },
  {
    customerName: 'Jose Hernandez',
    customerPhone: '555-0103',
    addressLink: 'https://maps.google.com/?q=Palacio+de+Bellas+Artes,Mexico+City',
    status: 'En Route',
    createdAt: subDays(new Date(), 1).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 3,
  },
  {
    customerName: 'Ana Martinez',
    customerPhone: '555-0104',
    addressLink: 'https://maps.google.com/?q=Museo+Nacional+de+Antropologia,Mexico+City',
    status: 'Delivered',
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 2).toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 4,
    satisfaction: 5,
  },
  {
    customerName: 'Luis Rodriguez',
    customerPhone: '555-0105',
    addressLink: 'https://maps.google.com/?q=Coyoacan,Mexico+City',
    status: 'Pending',
    createdAt: subDays(new Date(), 3).toISOString(),
    updatedAt: subDays(new Date(), 3).toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 5,
  },
  {
    id: 'ETG-6',
    customerName: 'Sofia Lopez',
    customerPhone: '555-0106',
    addressLink: 'https://maps.google.com/?q=Xochimilco,Mexico+City',
    status: 'Delivered',
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: subDays(new Date(), 5).toISOString(),
    ownerId: 'admin1',
    driverId: 'driver1',
    priority: 6,
    satisfaction: 4,
  },
];
